// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ToteWait.h"
#include "../Robot.h"
ToteWait::ToteWait() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
ToteWait::ToteWait(double seconds){
//    std::cout << "Tote wait: " << seconds << std::endl;
    SetTimeout(seconds);
}
// Called just before this Command runs the first time
void ToteWait::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void ToteWait::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool ToteWait::IsFinished() {
    if((IsTimedOut()) || (!Robot::m_intake->IsFrontSensorTripped()))
        {
            return true;
        }
	return false;
}
// Called once after isFinished returns true
void ToteWait::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ToteWait::Interrupted() {
}
